#when you press add(+) an extra window is shown to chose your next category
# examples: 
## work -> programming, actually_@_work
## fun -> friends, sports, ...
## void (empty block for anything outside of normal categories or you forgot what it was?)
## house -> coocking, cleaning, ...
## inner peace -> meditation, reading, ...

#each main->category has it's own color
#set-up of timers and colors is via settings and configuration.py